name = "rsimd-items-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "rsimd_items_db"
database_id = "ff57f1b7-da26-490c-aaf7-19228acf16a1"

[[kv_namespaces]]
binding = "KV"
id = "f05fbbeeceb54cf695d6c8178f3c6fb1"

[[r2_buckets]]
binding = "R2"
bucket_name = "rsimd-items-files"

[ai]
binding = "AI"
